### PR TITLE
support agp 8

### PR DESCRIPTION
**Pull request by 0xera**

### CODE REVIEW

**Comment by natario1** [comment]
This is very impressive work @0xera, thanks! 👏 I will look into it today or tomorrow.

**Review by natario1 — APPROVED** [review]
Impressive work. Thank you.

**Comment by natario1** [comment]
Is this ready to be merged? I saw you pushed minor changes recently. It looks good to me, I may just change the API surface in GreaseExtension a bit before release.

**Comment by 0xera** [comment]
Yeah. it's ready to merge, i think

**Pull request merged**
