### PR TITLE
add dependencies from grease configuration to compileOnly

### PR DESCRIPTION
**Pull request by 0xera**

### CODE REVIEW

**Comment by natario1** [comment]
Were you able to reproduce #11? As I remember using compileClasspath already makes compilation work. And compileOnly creates problem downstream because it adds the dependency to the POM. I think we should have a reproducer for #11 first

**Comment by 0xera** [comment]
I tried to publish the library with compileOnly and the dependency did not appear in the pom file. I also found this discussion https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903 And checked old fat aar plugins - they also add dependencies with compileOnly. This trick seems to work

**Comment by 0xera** [comment]
I have found why there is a problem with META-INF. It is because shadow jar uses Gradle Api from 8.3 version, so building a library with lower version than 8.3 will led to the crash. We could write about these limitations in the README

Снимок экрана 2024-09-29 в 12 50 36
Снимок экрана 2024-09-29 в 12 50 46

**Comment by 0xera** [comment]
Hi, @natario1 I have added a functional test and you can run it to make sure that compileOnly dependencies are not in a pom file

**Review by natario1 — APPROVED** [review]

**Comment by natario1** [comment]
@0xera I approved it, my doubt is whether this really fixes anything. `compileClasspath` always worked well regarding adding deps to the compilation classpath, so if it works we shouldn't change it. But feel free to merge if you reproduced issues with `compileClasspath` that are solved by `compileOnly`.

**Pull request merged**
